/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AJMM
 */
public class unCorreoEnviadoFrame extends javax.swing.JFrame {

    /**
     * Creates new form unCorreoEnviadoFrame
     */
    public unCorreoEnviadoFrame(String asunto, String[] destinatarios, Object contenido, boolean esTexto) {
        initComponents();
        //pongo los que son faciles de poner (destinatario y asunto)
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        this.asuntoLabel.setText(asunto);
        for (String destinatario : destinatarios) {
            ((DefaultTableModel)destinatariosTable.getModel()).addRow(new Object[1]);
            destinatariosTable.setValueAt(destinatario, destinatariosTable.getRowCount() - 1, 0);
        }
        destinatariosTable.setPreferredScrollableViewportSize(new Dimension(400, destinatariosTable.getRowCount() * destinatariosTable.getRowHeight()));
        
        //consigo el cuerpo y el nombre de los adjuntos
        String cuerpo = null;
        if (esTexto){
            // mensaje de texto simple
             cuerpo = (String) contenido;
        
        }
        else{
            
        }
        
        ArrayList<String> adjuntosNombres = new ArrayList<>();
        
        this.contenidoTextArea.setText(cuerpo);
        for (String adjunto : adjuntosNombres) {
            ((DefaultTableModel)adjuntosTable.getModel()).addRow(new Object[1]);
            adjuntosTable.setValueAt(adjunto, adjuntosTable.getRowCount() - 1, 0);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        destinatariosTable = new javax.swing.JTable();
        asuntoSoloParaUILabel = new javax.swing.JLabel();
        asuntoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contenidoTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        adjuntosTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        destinatariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Destinatarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(destinatariosTable);

        asuntoSoloParaUILabel.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        asuntoSoloParaUILabel.setText("Asunto:");

        asuntoLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        asuntoLabel.setText(".");

        contenidoTextArea.setEditable(false);
        contenidoTextArea.setColumns(20);
        contenidoTextArea.setRows(5);
        jScrollPane2.setViewportView(contenidoTextArea);

        adjuntosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Adjuntos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(adjuntosTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(asuntoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asuntoSoloParaUILabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asuntoSoloParaUILabel)
                        .addGap(7, 7, 7)
                        .addComponent(asuntoLabel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adjuntosTable;
    private javax.swing.JLabel asuntoLabel;
    private javax.swing.JLabel asuntoSoloParaUILabel;
    private javax.swing.JTextArea contenidoTextArea;
    private javax.swing.JTable destinatariosTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
